### ISSUE TITLE
Fallback Behavior in case our localization fails

### ISSUE THREAD

**Issue by NFiedler** [bit-bots/bitbots_behavior#13]
We need a behavior to use when the self-localization does not work. It should rely on relative messages.
Note for later: When the world model is in use (somewhere in the future), the local model message needs to be used.

**Comment by ftsell** [comment]
Are you sure this is a behavior issue?

I can see the point that if the behavior decides not to use normal localisation - for example if it determines that to be inaccurate - it should switch to the proposed method.

An alternative solution would be that the localisation itself sorts this out and the behavior focuses more on decisions like strategy.

**Comment by timonegk** [comment]
This is indeed a behavior issue. Since the behavior heavily relies on the localization, but the localization itself does not always work perfectly, an alternative is crucial. Due to the structure of numerous decisions, it is not possible to solve the problem inside of the localization. If you think in human terms, it would also be a behavioral problem to act accordingly when the own position is not known.

The issue could be solved by adding a simple decision that checks whether localization messages are received and how much accuracy the covariance matrix suggests. Subsequent decisions and actions should, as @NFiedler mentioned, rely on relative data only, either by reusing existing decisions with a DSD parameter or by implementing them from scratch where necessary.

**Comment by timonegk** [comment]
This general issue is mostly fixed and should be replaced with more detailed issues that occur in the future.
