### ISSUE TITLE
Head Behavior: Head collides with shoulder

### ISSUE THREAD

**Issue by Flova** [bit-bots/bitbots_behavior#55]
As Niklas said, the new head sometimes collides with the shoulder.
This should be fixed for the search pattern and tracking modes.

**Comment by NFiedler** [comment]
Is this still an issue?

**Comment by NFiedler** [comment]
This still is a big issue and has to be addressed. While looking around we don't hit the shoulder but when tracking the ball we do. Thus it is possible that the robot collapses due to an overload error every time the ball rolls past it. 
We have basically two options:
- **Fix the Hardware**: We shorten the head in the front 
- **Fix the Software**: We use moveit stuff to prevent the collision

**Comment by 16stelter** [comment]
I don't think this problem can be solved by changing the hardware easily since the camera itself is pretty long. Only way would be to move the camera further back when we switch to power over ethernet and get rid of the power cable.

**Comment by SammyRamone** [comment]
It is still an issue with current hardware. We could do collision checking, the updated URDF can provide an accurate enough collision model, but it would require some work.
Setting the camera further back is the better option in my oppinion, since the new cables allow us to shorten the head

**Comment by Flova** [comment]
Also the new head leaves way more space between the front of head and the lens, this was not the case with previous versions and could be shortened easily while still containing enough room to protect the optics e.g. at a fall.

**Comment by JanGut** [comment]
Is this still an issue with the new hardware? I could test this tomorrow...

**Comment by JanGut** [comment]
Yes, unfortunately, it is.
